/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as VersionThreeRouteImport } from './routes/version-three'
import { Route as VersionTwoRouteImport } from './routes/version-two'
import { Route as ApiCareersRouteImport } from './routes/api.careers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionThreeRoute = VersionThreeRouteImport.update({
  id: '/version-three',
  path: '/version-three',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionTwoRoute = VersionTwoRouteImport.update({
  id: '/version-two',
  path: '/version-two',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareersRoute = ApiCareersRouteImport.update({
  id: '/api/careers',
  path: '/api/careers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/version-three': typeof VersionThreeRoute
  '/version-two': typeof VersionTwoRoute
  '/api/careers': typeof ApiCareersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/version-three': typeof VersionThreeRoute
  '/version-two': typeof VersionTwoRoute
  '/api/careers': typeof ApiCareersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/version-three': typeof VersionThreeRoute
  '/version-two': typeof VersionTwoRoute
  '/api/careers': typeof ApiCareersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/careers' | '/version-three' | '/version-two' | '/api/careers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/careers' | '/version-three' | '/version-two' | '/api/careers'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/version-three'
    | '/version-two'
    | '/api/careers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  VersionThreeRoute: typeof VersionThreeRoute
  VersionTwoRoute: typeof VersionTwoRoute
  ApiCareersRoute: typeof ApiCareersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version-three': {
      id: '/version-three'
      path: '/version-three'
      fullPath: '/version-three'
      preLoaderRoute: typeof VersionThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version-two': {
      id: '/version-two'
      path: '/version-two'
      fullPath: '/version-two'
      preLoaderRoute: typeof VersionTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/careers': {
      id: '/api/careers'
      path: '/api/careers'
      fullPath: '/api/careers'
      preLoaderRoute: typeof ApiCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  VersionThreeRoute: VersionThreeRoute,
  VersionTwoRoute: VersionTwoRoute,
  ApiCareersRoute: ApiCareersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
