/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersionThreeRouteImport } from './routes/version-three'
import { Route as VersionTwoRouteImport } from './routes/version-two'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionThreeRoute = VersionThreeRouteImport.update({
  id: '/version-three',
  path: '/version-three',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionTwoRoute = VersionTwoRouteImport.update({
  id: '/version-two',
  path: '/version-two',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/version-three': typeof VersionThreeRoute
  '/version-two': typeof VersionTwoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/version-three': typeof VersionThreeRoute
  '/version-two': typeof VersionTwoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/version-three': typeof VersionThreeRoute
  '/version-two': typeof VersionTwoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/version-three' | '/version-two'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/version-three' | '/version-two'
  id: '__root__' | '/' | '/version-three' | '/version-two'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VersionThreeRoute: typeof VersionThreeRoute
  VersionTwoRoute: typeof VersionTwoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version-three': {
      id: '/version-three'
      path: '/version-three'
      fullPath: '/version-three'
      preLoaderRoute: typeof VersionThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version-two': {
      id: '/version-two'
      path: '/version-two'
      fullPath: '/version-two'
      preLoaderRoute: typeof VersionTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VersionThreeRoute: VersionThreeRoute,
  VersionTwoRoute: VersionTwoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
